# -*- coding: utf-8 -*-
"""Projeto Final IoT - Hugo - DIO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZVxlX8w-rzPePVVdRrYQQf1T2NvKA0U6
"""

# Commented out IPython magic to ensure Python compatibility.
# Passo 1: Instalação e Configuração
!pip install -U numpy opencv-python-headless torch torchvision
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

# Passo 2: Baixar a Imagem de Teste
import urllib.request
import cv2
import matplotlib.pyplot as plt

image_url = 'https://github.com/user-attachments/assets/aa949488-316f-41f8-8fb7-40f1a6f8184c'
image_path = 'test_image.jpg'
urllib.request.urlretrieve(image_url, image_path)

def load_image(path):
    image = cv2.imread(path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    plt.imshow(image)
    plt.axis('off')
    plt.show()
    return image

image = load_image(image_path)

# Passo 3: Carregar o Modelo YOLOv5 Pré-treinado
import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Passo 5: Fazer a Predição na Imagem de Teste
results = model(image_path)
results.show()